services:
  - type: web
    name: shoof-howlz-backend
    env: node
    buildCommand: npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://shoof-howlz.vercel.app
      - key: PORT
        value: 10000
    plan: free